CREATE DATABASE salad;

USE salad;

CREATE TABLE member(
	mbr_Id 		VARCHAR(30) NOT NULL UNIQUE,
    mbr_Pwd		VARCHAR(50) NOT NULL,
    mbr_Name 	VARCHAR(10) NOT NULL,
    mbr_Email	VARCHAR(200) NOT NULL,
    PRIMARY KEY(mbr_Id)
);

CREATE TABLE clubLogs(
	mbr_Name 	VARCHAR(10) NOT NULL,
    clbL_Team	VARCHAR(200) NOT NULL,	# MEMBERS WHO WORK TOGETHER
    clbL_Date	DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    clbL_Dept	VARCHAR(20) NOT NULL,	# WEB / ANDROID APPLICATION
	clbL_Title 	VARCHAR(100) NOT NULL UNIQUE, 	# NEED NAMING RULE
    clbL_Content	VARCHAR(10000) NOT NULL,
    PRIMARY KEY(clbL_Title)
);

CREATE TABLE freeBoard(
	mbr_Name 	VARCHAR(10) NOT NULL,
    frB_Id		INT NOT NULL UNIQUE AUTO_INCREMENT,
    frB_Date	DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    frB_Title	VARCHAR(100) NOT NULL,
    frB_Content	VARCHAR(10000) NOT NULL,
    PRIMARY KEY(frB_Id)
);

show tables